### ISSUE TITLE
Support portable mode 

### ISSUE THREAD

**Issue by fbehrens** [alefragnani/vscode-project-manager#221]
[Portable mode](https://code.visualstudio.com/docs/editor/portable) is in a few months, and allows program, extensions and user configuration under one folder ( on a USB Stick)

I am using it on Windows, but Project-Manager does not detect portable mode.
So it fails create `projects.json` in the old default folder, which is not present.

```
[2018-09-15 09:54:23.024] [renderer1] [error] ENOENT: no such file or directory, open 'C:\Users\imynv\AppData\Roaming\Code\User\projects.json': Error: ENOENT: no such file or directory, open 'C:\Users\imynv\AppData\Roaming\Code\User\projects.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at ProjectStorage.save (D:\tools\VSCode\data\extensions\alefragnani.project-manager-8.0.0\out\src\storage.js:226:12)
    at vscode.window.showErrorMessage.then.option (D:\tools\VSCode\data\extensions\alefragnani.project-manager-8.0.0\out\src\extension.js:206:36)
    at Object.g [as _notify] (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:79:572)
    at Object.enter (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:924)
    at n.Class.derive._oncancel._run (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:790)
    at n.Class.derive._oncancel._completed (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:231)
    at e.resolveOk (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:578:1000)
    at e._receiveReply (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:680:669)
    at e._receiveOneMessage (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:344)
    at d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
    at d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
    at e.fire (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
    at a (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
    at Socket._socketDataListener (d:\tools\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

A workaround is to set 
```
 "projectManager.projectsLocation": "D:\\tools\\VSCode\\data\\user-data\\User",
```

**Comment by alefragnani** [comment]
Hi @fbehrens ,

The Portable Mode issue has already been reported in #201 (and also a PR #204 that suggests a fix), but recently I didn't have free time to update the extension to properly support it. As you also reported, there is a workaround, and you are able to use the extension, which is good 👍 

Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. But this "re-focus" will be based on _community feedback/support_, and I still don't know _where_ the Portable Mode will be. I suggest you to follow #201 for news. 

Hope this helps.
