### ISSUE TITLE
command 'projectManager.saveProjects' not found

### ISSUE THREAD

**Issue by CrisLi** [alefragnani/vscode-project-manager#77]
After I upgrade to the latest version of this ext, it doesn't work anymore.

The error is `command 'projectManager.editProjects' not found`.

OS Version: OSX 10.11.5
VS code version: Version 1.8.1 (1.8.1)

Is this defect for the new version?

Log: 

```js
[Extension Host] Here is the error stack:  TypeError: Cannot read property 
'toLocaleLowerCase' of undefined
    at ProjectStorage.existsWithRootPath (/Users/chris/.vscode/extensions/alefragnani.project-manager-0.13.0/out/storage.js:129:33)
    at showStatusBar (/Users/chris/.vscode/extensions/alefragnani.project-manager-0.13.0/out/extension.js:93:43)
    at activate (/Users/chris/.vscode/extensions/alefragnani.project-manager-0.13.0/out/extension.js:52:5)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:30819)
    at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:30602)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:30468
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:31009)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:2571)
    at _run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:4399)
    at _completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3840)
    at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:7378)
    at J.then.o.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:7595)
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:31009)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:2571)
    at _run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:4399)
    at _completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:3840)
```

**Comment by alefragnani** [comment]
Hi @CrisLi ,

Maybe you had the same problem as https://github.com/alefragnani/vscode-project-manager/issues/78. Could you check your `projects.json` file?

**Comment by CrisLi** [comment]
@alefragnani 
After I clean the `~/Library/Application Support/Code/User/projects.json` and resave the projects, it works fine.



Thanks
