### ISSUE TITLE
Error loading projects: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by zqjimlove** [alefragnani/vscode-project-manager#78]
shell.ts:541Cannot read property 'replace' of undefined: TypeError: Cannot read property 'replace' of undefined
    at /Users/inwoo/.vscode/extensions/alefragnani.project-manager-0.13.0/out/sorter.js:8:25
    at Array.sort (native)
    at Function.ProjectsSorter.getSortedByName (/Users/inwoo/.vscode/extensions/alefragnani.project-manager-0.13.0/out/sorter.js:6:33)
    at Function.ProjectsSorter.SortItemsByCriteria (/Users/inwoo/.vscode/extensions/alefragnani.project-manager-0.13.0/out/sorter.js:76:39)
    at sortProjectList (/Users/inwoo/.vscode/extensions/alefragnani.project-manager-0.13.0/out/extension.js:224:54)
    at /Users/inwoo/.vscode/extensions/alefragnani.project-manager-0.13.0/out/extension.js:399:20
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by zqjimlove** [comment]
oh~I fixed it.
I found a item didn't set `name` in my `project.json` .
then I found other problem~

```javascript
vscode.window.showInformationMessage('Error loading projects: ${reason}');
```

you should use `\`` not `'`
